import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { DYNASTY_DECISION_DOC_PATH } from '../src/ui/FootballHubScreen';

describe('dynasty decision roadmap', () => {
  it('marks the first dynasty phase complete and keeps the hub shell pointed at the decision map', () => {
    const decisionDoc = readFileSync(DYNASTY_DECISION_DOC_PATH, 'utf8');

    expect(DYNASTY_DECISION_DOC_PATH).toBe('docs/DYNASTY_DECISIONS.md');
    expect(decisionDoc).toContain('### Phase 0: Dynasty Shell');
    expect(decisionDoc).toContain('Status: Complete in `1.22.0`.');
    expect(decisionDoc).toContain('The Dynasty destination is a non-playable planning shell.');
    expect(decisionDoc).toContain('Status: Complete in `1.22.19`.');
    expect(decisionDoc).toContain('Season-core contract: add the `DynastySaveData` schema');
    expect(decisionDoc).toContain('Save repository: persist, load, reset, and migrate the active dynasty save');
    expect(decisionDoc).toContain('Dynasty hub view: show the active user program');
    expect(decisionDoc).toContain('Weekly advance: simulate non-user games deterministically');
    expect(decisionDoc).toContain('Reload and migration hardening: validate corrupt saves');
    expect(decisionDoc).toContain('Flow hardening: prevent Play Now and Dynasty state from leaking into each other');
    expect(decisionDoc).toContain('Dynasty matchup launch settings are runtime-only');
    expect(decisionDoc).toContain('### Phase 2: Stats, Stories, and Awards');
    expect(decisionDoc).toContain('Status: Complete in `1.22.25`.');
    expect(decisionDoc).toContain('Season stats contract: add team-level season stat rows');
    expect(decisionDoc).toContain('Weekly leaders: expose passing, rushing, scoring, turnover, and yardage leaders');
    expect(decisionDoc).toContain('Story hooks: add compact Dynasty context summaries');
    expect(decisionDoc).toContain('Award watch lists: add deterministic offensive, defensive, and special teams watch rows');
    expect(decisionDoc).toContain('Stat validation hardening: reject missing, negative, mismatched, or impossible aggregate stat rows');
    expect(decisionDoc).toContain('Story presentation hardening: keep Dynasty story copy generic, factual, and absent from Play Now');
    expect(decisionDoc).toContain('Dynasty story copy is suppressed for Play Now and for malformed Dynasty context.');
    expect(decisionDoc).toContain('Patch hardening plan:');
    expect(decisionDoc).toContain('### Phase 3: Player Progression');
    expect(decisionDoc).toContain('Status: Complete in `1.22.31`.');
    expect(decisionDoc).toContain('Progression preview contract: add deterministic presentation-only performance points');
    expect(decisionDoc).toContain('Weekly training summary: add a compact hub section that groups projected development by position room and archetype. Shipped in `1.22.27`.');
    expect(decisionDoc).toContain('Rating delta preview: calculate bounded projected attribute and overall changes based on position weights, still not applied to gameplay. Shipped in `1.22.28`.');
    expect(decisionDoc).toContain('Apply-to-save progression: persist approved end-of-week progression rows and roster rating deltas in Dynasty save data. Shipped in `1.22.29`.');
    expect(decisionDoc).toContain('Progression bounds hardening: reject negative, non-integer, oversized, or duplicate progression rows during save validation. Shipped in `1.22.30`.');
    expect(decisionDoc).toContain('Gameplay isolation hardening: prove progression previews and saved deltas cannot alter live gameplay ratings until explicitly applied through the approved path. Shipped in `1.22.31`.');
    expect(decisionDoc).toContain('Approved progression applications persist player/week rating delta history in the save without mutating roster registry ratings.');
    expect(decisionDoc).toContain('### Phase 4: Recruiting-Lite');
    expect(decisionDoc).toContain('Status: Complete in `1.22.37`.');
    expect(decisionDoc).toContain('Prospect pool contract: add deterministic fictional prospects, position/archetype metadata, star grades, and three pitch-style fit scores without changing rosters. Shipped in `1.22.32`.');
    expect(decisionDoc).toContain('Team needs view: derive compact recruiting needs from current roster composition and ratings. Shipped in `1.22.33`.');
    expect(decisionDoc).toContain('Weekly recruiting points: add a simple points allocation model for the user program. Shipped in `1.22.34`.');
    expect(decisionDoc).toContain('Signing class preview: summarize likely signees and class fit without mutating rosters until offseason work. Shipped in `1.22.35`.');
    expect(decisionDoc).toContain('Recruiting validation hardening: reject duplicate prospects, invalid pitch scores, impossible grades, and malformed interest rows. Shipped in `1.22.36`.');
    expect(decisionDoc).toContain('Roster safety hardening: prove recruiting views and saved allocations cannot change active roster size or gameplay lineups before the offseason apply path. Shipped in `1.22.37`.');
    expect(decisionDoc).toContain('Dynasty Recruiting-Lite now creates a deterministic fictional prospect pool');
    expect(decisionDoc).toContain('Recruiting roster safety snapshots and gameplay binding checks prove recruiting allocations');
    expect(decisionDoc).toContain('### Phase 5: Program Management');
    expect(decisionDoc).toContain('Status: Complete in `1.22.43`.');
    expect(decisionDoc).toContain('Coach goals contract: add visible weekly and season program goals derived from save state without changing gameplay outcomes. Shipped in `1.22.38`.');
    expect(decisionDoc).toContain('Program strengths view: summarize the user program\'s identity from roster ratings, team stats, and standings. Shipped in `1.22.39`.');
    expect(decisionDoc).toContain('Budget allocation model: add a simple visible allocation between recruiting, training, facilities, and staff. Shipped in `1.22.40`.');
    expect(decisionDoc).toContain('Staff modifiers preview: show small deterministic staff bonuses as future-phase inputs, not current-play effects. Shipped in `1.22.41`.');
    expect(decisionDoc).toContain('Program management validation hardening: reject malformed goals, budget totals, hidden modifiers, and out-of-range bonus values. Shipped in `1.22.42`.');
    expect(decisionDoc).toContain('Gameplay isolation hardening: prove program goals, budgets, and staff modifiers cannot alter current-play ratings, movement, or simulation results before approved apply paths exist. Shipped in `1.22.43`.');
    expect(decisionDoc).toContain('Dynasty Program Management now exposes visible coach goals');
    expect(decisionDoc).toContain('Program Management previews are future-phase-only and gameplay isolation coverage proves');
    expect(decisionDoc).toContain('### Phase 6: Offseason and Multi-Year Saves');
    expect(decisionDoc).toContain('Status: Complete in `1.22.49`.');
    expect(decisionDoc).toContain('Departures preview contract: add deterministic offseason departure candidates from roster identity and season status without mutating rosters. Shipped in `1.22.44`.');
    expect(decisionDoc).toContain('Incoming class preview: connect recruiting signing previews to an offseason incoming class without mutating rosters. Shipped in `1.22.45`.');
    expect(decisionDoc).toContain('Roster review: show returning, departing, and incoming balance with position gaps. Shipped in `1.22.46`.');
    expect(decisionDoc).toContain('Next-season schedule and history: generate the next season shell and preserve season history rows. Shipped in `1.22.47`.');
    expect(decisionDoc).toContain('Offseason validation hardening: reject malformed departures, incoming class rows, roster review rows, duplicate history entries, and invalid next-season metadata. Shipped in `1.22.48`.');
    expect(decisionDoc).toContain('Multi-year save isolation hardening: prove offseason previews and next-season shells cannot corrupt active roster registry, current-season results, or save migration paths. Shipped in `1.22.49`.');
    expect(decisionDoc).toContain('Dynasty Offseason now exposes deterministic departure previews');
    expect(decisionDoc).toContain('Offseason validation rejects malformed departure candidates');
    expect(decisionDoc).toContain('Multi-year isolation coverage proves offseason previews and next-season shells do not alter current-season results');
  });
});
