import { PLAYABLE_FIELD_BOUNDS } from '../field';
import type { PresentationCameraConfig } from './CameraTypes';

export const GAMEPLAY_CAMERA_CONFIG = {
  offensePerspective: {
    ballCenterNdcTolerance: 0.35,
    distanceBehindFocus: 30,
    fieldOfView: 48,
    forwardLookAhead: 18,
    height: 17,
    liveBallLookAhead: 8,
    maximumFieldPosition: {
      x: PLAYABLE_FIELD_BOUNDS.maxX,
      z: PLAYABLE_FIELD_BOUNDS.maxZ,
    },
    minimumFieldPosition: {
      x: PLAYABLE_FIELD_BOUNDS.minX,
      z: PLAYABLE_FIELD_BOUNDS.minZ,
    },
    passFlightLookAhead: 3.5,
    positionSmoothing: 8,
    targetSmoothing: 10,
  },
  playDirection: {
    x: 0,
    z: 1,
  },
  tacticalOrthographic: {
    narrowAspectThreshold: 0.75,
    narrowViewHeight: 155,
    position: {
      x: 18,
      y: 74,
      z: -110,
    },
    target: {
      x: 0,
      y: 0,
      z: 0,
    },
    wideViewHeight: 96,
  },
} as const;

export const PRESENTATION_CAMERA_CONFIG: PresentationCameraConfig = {
  cinematics: {
    fieldPadding: 52,
    firstDownCrowdCutaway: {
      briefDuration: 0.75,
      briefSweepDegrees: 12,
      distance: 16,
      fieldOfView: 34,
      fullDuration: 1.1,
      fullSweepDegrees: 20,
      height: 7,
      lookAhead: 0,
      maximumRadius: 24,
      minimumRadius: 12,
      sidelineOffset: 0,
    },
    minimumCameraHeight: 5.5,
    prePlayOrbit180: {
      briefDuration: 1.05,
      briefSweepDegrees: 145,
      distance: 32,
      fieldOfView: 42,
      fullDuration: 1.55,
      fullSweepDegrees: 180,
      height: 30,
      lookAhead: 4,
      maximumRadius: 58,
      minimumRadius: 28,
      sidelineOffset: 0,
    },
    touchdownCrowdCutaway: {
      briefDuration: 0.8,
      briefSweepDegrees: 18,
      distance: 17,
      fieldOfView: 34,
      fullDuration: 1.2,
      fullSweepDegrees: 30,
      height: 7.5,
      lookAhead: 0,
      maximumRadius: 26,
      minimumRadius: 13,
      sidelineOffset: 0,
    },
    touchdownOrbit360: {
      briefDuration: 0.8,
      briefSweepDegrees: 270,
      distance: 20,
      fieldOfView: 40,
      fullDuration: 1.05,
      fullSweepDegrees: 350,
      height: 9,
      lookAhead: -4,
      maximumRadius: 34,
      minimumRadius: 16,
      sidelineOffset: 0,
    },
  },
  fieldOfView: 44,
  holdPreSnapEstablish: false,
  maximumFieldPosition: {
    x: PLAYABLE_FIELD_BOUNDS.maxX,
    z: PLAYABLE_FIELD_BOUNDS.maxZ,
  },
  maximumTransitionSpeed: 85,
  maxDeltaSeconds: 0.05,
  minimumFieldPosition: {
    x: PLAYABLE_FIELD_BOUNDS.minX,
    z: PLAYABLE_FIELD_BOUNDS.minZ,
  },
  phases: {
    deadBallResult: {
      distance: 22,
      height: 12,
      lookAhead: 4,
      shotDuration: 0.8,
    },
    liveCarrier: {
      distance: 24,
      height: 13,
      lookAhead: 16,
      positionSmoothing: 7.5,
      shotDuration: 0,
      targetSmoothing: 9,
    },
    passFlight: {
      distance: 28,
      height: 18,
      lookAhead: 6,
      positionSmoothing: 9,
      shotDuration: 0,
      targetSmoothing: 11,
    },
    preSnapEstablish: {
      distance: 44,
      height: 38,
      lookAhead: 6,
      positionSmoothing: 5.5,
      shotDuration: 1.2,
      sidelineOffset: 8,
      targetSmoothing: 6,
    },
    returnToPreSnap: {
      distance: 30,
      height: 19,
      lookAhead: 10,
      shotDuration: 0.8,
    },
    touchdownResult: {
      distance: 18,
      height: 8,
      lookAhead: -6,
      positionSmoothing: 6,
      shotDuration: 0.95,
      sidelineOffset: 7,
      targetSmoothing: 8,
    },
    transitionToGameplay: {
      distance: 30,
      height: 20,
      lookAhead: 14,
      positionSmoothing: 8,
      shotDuration: 0.45,
      targetSmoothing: 9,
    },
  },
  playDirection: {
    x: 0,
    z: 1,
  },
  positionSmoothing: 7,
  targetSmoothing: 8,
} as const;
