export const LOCAL_PREGAME_COMMENTARY_ASSET_IDS = [
  'pregame_coin_toss_result_bay-city-current_kick_01',
  'pregame_coin_toss_result_bay-city-current_receive_01',
  'pregame_coin_toss_result_generic_01',
  'pregame_coin_toss_result_generic_02',
  'pregame_coin_toss_result_lakefront-lights_kick_01',
  'pregame_coin_toss_result_lakefront-lights_receive_01',
  'pregame_coin_toss_result_metro-meteors_kick_01',
  'pregame_coin_toss_result_metro-meteors_receive_01',
  'pregame_coin_toss_result_summit-forge_kick_01',
  'pregame_coin_toss_result_summit-forge_receive_01',
  'pregame_coin_toss_setup_01',
  'pregame_coin_toss_setup_02',
  'pregame_kickoff_in_flight_01',
  'pregame_kickoff_in_flight_02',
  'pregame_kickoff_ready_01',
  'pregame_kickoff_ready_02',
  'pregame_kickoff_ready_03',
  'pregame_kickoff_result_deep_kick_01',
  'pregame_kickoff_result_deep_kick_02',
  'pregame_kickoff_result_returned_kick_01',
  'pregame_kickoff_result_returned_kick_02',
  'pregame_kickoff_result_short_kick_01',
  'pregame_kickoff_result_short_kick_02',
  'pregame_kickoff_result_touchback_01',
  'pregame_kickoff_result_touchback_02',
  'pregame_qb_bay-city-current-qb-6_01',
  'pregame_qb_bay-city-current-qb-6_02',
  'pregame_qb_bay-city-current-qb-6_03',
  'pregame_qb_lakefront-lights-qb-8_01',
  'pregame_qb_lakefront-lights-qb-8_02',
  'pregame_qb_lakefront-lights-qb-8_03',
  'pregame_qb_metro-meteors-qb-12_01',
  'pregame_qb_metro-meteors-qb-12_02',
  'pregame_qb_metro-meteors-qb-12_03',
  'pregame_qb_summit-forge-qb-14_01',
  'pregame_qb_summit-forge-qb-14_02',
  'pregame_qb_summit-forge-qb-14_03',
  'pregame_warmup_transition_01',
  'pregame_warmup_transition_02',
  'pregame_weather_clear_01',
  'pregame_weather_clear_02',
  'pregame_weather_overcast_01',
  'pregame_weather_overcast_02',
  'pregame_weather_rain_01',
  'pregame_weather_rain_02',
  'pregame_weather_snow_01',
  'pregame_weather_snow_02',
  'pregame_weather_windy_01',
  'pregame_weather_windy_02',
  'pregame_welcome_01',
  'pregame_welcome_02',
  'pregame_welcome_03',
] as const;

const LOCAL_PREGAME_COMMENTARY_ASSET_ID_SET = new Set<string>(
  LOCAL_PREGAME_COMMENTARY_ASSET_IDS,
);

export function isLocalPregameCommentaryAssetId(assetId: string | null | undefined): boolean {
  return typeof assetId === 'string' && LOCAL_PREGAME_COMMENTARY_ASSET_ID_SET.has(assetId);
}
