import {
  assertValidAudioPlan,
  createAudioPlanReport,
  isDirectCli,
  type AudioAssetPlan,
} from './schemas';

const SOUND_EFFECT_MODEL = 'eleven_text_to_sound_v2';
const WEB_OUTPUT_FORMAT = 'mp3_44100_128';
const PROMPT_INTEGRITY =
  'No speech, no intelligible chants, no announcer, no music, no copyrighted recording, no real stadium imitation.';

export const FOOTBALL_AUDIO_PLAN: readonly AudioAssetPlan[] = [
  {
    assetId: 'crowd_idle_loop_01',
    category: 'crowd',
    kind: 'loop',
    prompt: [
      'Seamless 30 second looping ambience for a large outdoor American-football stadium.',
      'Steady anticipatory crowd murmur with distant scattered cheers.',
      'Wide stadium perspective, restrained energy, natural loop point.',
      PROMPT_INTEGRITY,
    ].join(' '),
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 30,
    loop: true,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/crowd/crowd_idle_loop_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'stream',
    maxBytes: 620_000,
    notes: 'Prototype streamed crowd bed for calm pre-snap and between-play ambience.',
  },
  {
    assetId: 'crowd_pressure_loop_01',
    category: 'crowd',
    kind: 'loop',
    prompt: [
      'Seamless 30 second looping ambience from the same large outdoor American-football stadium perspective.',
      'Urgent sustained crowd energy and pressure without a peak or climax.',
      'Natural loop point, broad crowd texture, no individual voice should be understood.',
      PROMPT_INTEGRITY,
    ].join(' '),
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 30,
    loop: true,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/crowd/crowd_pressure_loop_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'stream',
    maxBytes: 620_000,
    notes: 'Prototype streamed crowd bed for late-down or pressure moments.',
  },
  {
    assetId: 'crowd_first_down_01',
    category: 'crowd',
    kind: 'oneShot',
    prompt: [
      'Large outdoor American-football crowd quick positive swell after a first down, then natural decay.',
      'Three to four seconds, medium excitement, no long climax.',
      PROMPT_INTEGRITY,
    ].join(' '),
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 3.5,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/crowd/crowd_first_down_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 110_000,
    notes: 'First-down reaction variation A.',
  },
  {
    assetId: 'crowd_first_down_02',
    category: 'crowd',
    kind: 'oneShot',
    prompt: [
      'Large outdoor American-football crowd quick positive first-down reaction with a slightly brighter swell and natural decay.',
      'Three to four seconds, no announcer or words.',
      PROMPT_INTEGRITY,
    ].join(' '),
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 3.6,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/crowd/crowd_first_down_02.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 115_000,
    notes: 'First-down reaction variation B.',
  },
  {
    assetId: 'crowd_touchdown_01',
    category: 'crowd',
    kind: 'oneShot',
    prompt: [
      'Large outdoor American-football crowd explosive touchdown celebration with a natural tail.',
      'Seven to nine seconds, big positive release, wide stadium perspective.',
      PROMPT_INTEGRITY,
    ].join(' '),
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 8,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/crowd/crowd_touchdown_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 180_000,
    notes: 'Touchdown celebration variation A.',
  },
  {
    assetId: 'crowd_touchdown_02',
    category: 'crowd',
    kind: 'oneShot',
    prompt: [
      'Large outdoor American-football crowd explosive touchdown celebration with rolling cheers and natural tail.',
      'Seven to nine seconds, energetic but not musical.',
      PROMPT_INTEGRITY,
    ].join(' '),
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 8.5,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/crowd/crowd_touchdown_02.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 190_000,
    notes: 'Touchdown celebration variation B.',
  },
  {
    assetId: 'crowd_incomplete_01',
    category: 'crowd',
    kind: 'oneShot',
    prompt: [
      'Large outdoor American-football crowd collective disappointed reaction after an incomplete pass.',
      'About three seconds, quick letdown and natural decay.',
      PROMPT_INTEGRITY,
    ].join(' '),
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 3,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/crowd/crowd_incomplete_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 100_000,
    notes: 'Incomplete-pass disappointed crowd reaction.',
  },
  {
    assetId: 'crowd_turnover_01',
    category: 'crowd',
    kind: 'oneShot',
    prompt: [
      'Large outdoor American-football crowd shocked disappointed reaction after a turnover on downs.',
      'Four to five seconds, bigger negative response with natural decay.',
      PROMPT_INTEGRITY,
    ].join(' '),
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 4.5,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/crowd/crowd_turnover_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 125_000,
    notes: 'Turnover or failed-fourth-down disappointed crowd reaction.',
  },
  {
    assetId: 'pads_hit_01',
    category: 'sfx',
    kind: 'oneShot',
    prompt: 'Short low-poly arcade-realistic American-football shoulder-pad collision: padded thump and plastic pop, no bones breaking, no explosion, no voice.',
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 0.9,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/sfx/pads_hit_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 65_000,
    notes: 'Pad collision variation A.',
  },
  {
    assetId: 'pads_hit_02',
    category: 'sfx',
    kind: 'oneShot',
    prompt: 'Short low-poly arcade-realistic American-football shoulder-pad collision with a tighter chest-pad bump, no bones breaking, no cinematic explosion, no voice.',
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 0.9,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/sfx/pads_hit_02.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 65_000,
    notes: 'Pad collision variation B.',
  },
  {
    assetId: 'pads_hit_03',
    category: 'sfx',
    kind: 'oneShot',
    prompt: 'Short low-poly arcade-realistic American-football shoulder-pad collision with a deeper padded body thud, no bones breaking, no exaggerated explosion, no voice.',
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 1,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/sfx/pads_hit_03.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 70_000,
    notes: 'Pad collision variation C.',
  },
  {
    assetId: 'ball_catch_01',
    category: 'sfx',
    kind: 'oneShot',
    prompt: 'Close football catch sound: leather football striking gloves and chest pads with a soft slap and fabric movement, no voice, no crowd.',
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 0.8,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/sfx/ball_catch_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 60_000,
    notes: 'Catch one-shot variation A.',
  },
  {
    assetId: 'ball_catch_02',
    category: 'sfx',
    kind: 'oneShot',
    prompt: 'Close football catch sound: leather ball hits gloves and chest pads, slightly sharper hand slap and jersey rustle, no voice, no crowd.',
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 0.8,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/sfx/ball_catch_02.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 60_000,
    notes: 'Catch one-shot variation B.',
  },
  {
    assetId: 'referee_whistle_01',
    category: 'sfx',
    kind: 'oneShot',
    prompt: 'Short clean referee dead-play whistle, crisp single whistle blast with small tail, no voice, no crowd, no music.',
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 1,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/sfx/referee_whistle_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 65_000,
    notes: 'Dead-play whistle one-shot.',
  },
  {
    assetId: 'snap_01',
    category: 'sfx',
    kind: 'oneShot',
    prompt: 'Compact American-football snap sound: quick ball movement, gloves, jersey and pad rustle, close microphone, no voice, no whistle, no crowd.',
    modelId: SOUND_EFFECT_MODEL,
    requestedDurationSeconds: 0.8,
    loop: false,
    outputFormat: WEB_OUTPUT_FORMAT,
    outputPath: 'public/audio/sfx/snap_01.mp3',
    generationStatus: 'planned',
    runtimeLoadingStrategy: 'buffer',
    maxBytes: 60_000,
    notes: 'Football snap and equipment movement one-shot.',
  },
] as const;

export function getFootballAudioPlan(): readonly AudioAssetPlan[] {
  return FOOTBALL_AUDIO_PLAN;
}

export function validateFootballAudioPlan(): string[] {
  try {
    assertValidAudioPlan(FOOTBALL_AUDIO_PLAN);
    return [];
  } catch (error) {
    return error instanceof Error ? error.message.split('\n').slice(1) : ['Unknown audio plan error'];
  }
}

if (isDirectCli(import.meta.url)) {
  assertValidAudioPlan(FOOTBALL_AUDIO_PLAN);
  console.log(JSON.stringify(createAudioPlanReport(FOOTBALL_AUDIO_PLAN), null, 2));
}
